### ISSUE TITLE
Define tasks in a file

### ISSUE THREAD

**Issue by martini97** [pianocomposer321/yabs.nvim#52]
Hey, I'm working on something similar to this, but instead of defining the tasks in lua code I'm defining them on yaml, something like this:
```yaml
taskname:
  command: make start
  output: quickfix
  env:
    - ENV_VAR: value
```
This allow the user to define tasks specifics to a project or global, kind like [asynctasks.vim](https://github.com/skywind3000/asynctasks.vim). Do you think this would be useful to yabs?
